### ISSUE TITLE
Criar serviço de checagem de permissões;

### ISSUE THREAD

**Issue by AdrielSantana** [SIEHP/siehp-api#28]
## Descrição

Utilizar um Enum do prisma para catalogar as permissões.

O serviço deve receber o ID do usuário e requisitá-lo pelo repositório trazendo suas permissões.

Como segundo parâmetro da função deve receber um array de permissões que ditará quais são as permissões para serem checadas.

Fazer a comparação levando em conta os relacionamentos das permissões contidas uma nas outras.

Checar documentação:

https://github.com/SIEHP/siehp-webapp/wiki/11.-Permiss%C3%B5es

## Testes

1. Utilizar esse serviço em algum controlador já instaciado antes do caso de uso.
2. Checar se para permissões diferentes está funcionando

## GitFlow

Criar uma Branch a partir de: `main`

É necessário abrir uma PR para as branchs a seguir:

- [ ] `main`
- [ ] `dev`

**Comment by Vitordotpy** [comment]
@AdrielSantana essa issue já foi testada ? a #34 aguarda merge
